Change lib:: references to bfl::
Fixes #11.

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -16,137 +16,137 @@
 #   This is a one dimensional array. Each element is a pipe delimited list
 #   of three values in this sequence:
 #
-#   1. Function to test (example: lib::implode)
+#   1. Function to test (example: bfl::implode)
 #   2. Parameters to pass to function (example, "1" "2" "3")
 #   3. Expected return code (example: 0)
 #------------------------------------------------------------------------------
 declare_assertions() {
   declare -ga assertions=(
-    'lib::declare_global_display_constants|"foo" "bar"|1'
-    'lib::declare_global_display_constants|"foo"|1'
-    'lib::declare_global_display_constants|""|1'
-    'lib::declare_global_display_constants||0'
-    'lib::echo_args|"foo" "bar"|0'
-    'lib::echo_args|"foo"|0'
-    'lib::echo_args|""|0'
-    'lib::echo_args||1'
-    'lib::die|"foo" "bar"|1'
-    'lib::die|"foo"|1'
-    'lib::die|""|1'
-    'lib::die||1'
-    'lib::find_nearest_integer||1'
-    'lib::find_nearest_integer||1'
-    'lib::find_nearest_integer|"" ""|1'
-    'lib::find_nearest_integer|"a" ""|1'
-    'lib::find_nearest_integer|"3" "a e g"|1'
-    'lib::find_nearest_integer|"3" ""|1'
-    'lib::find_nearest_integer|"3.1" "1 4 9"|1'
-    'lib::find_nearest_integer|"3" "1 4.1 9"|1'
-    'lib::find_nearest_integer|"3" "1 4 9"|0'
-    'lib::find_nearest_integer|"3" "2 4"|0'
-    'lib::find_nearest_integer|"3" "4"|0'
-    'lib::get_file_directory||1'
-    'lib::get_file_directory|""|1'
-    'lib::get_file_directory|"a" "b"|1'
-    'lib::get_file_directory|"/tmp/non-existent-file.ext"|1'
-    'lib::get_file_directory|"/etc/host.conf"|0'
-    'lib::get_file_extension||1'
-    'lib::get_file_extension|""|1'
-    'lib::get_file_extension|"a" "b"|1'
-    'lib::get_file_extension|"/tmp/non-existent-file.ext"|1'
-    'lib::get_file_extension|"/etc/host.conf"|0'
-    'lib::get_file_name||1'
-    'lib::get_file_name|""|1'
-    'lib::get_file_name|"a" "b"|1'
-    'lib::get_file_name|"/tmp/non-existent-file.ext"|1'
-    'lib::get_file_name|"/etc/host.conf"|0'
-    'lib::get_file_name_without_extension||1'
-    'lib::get_file_name_without_extension|""|1'
-    'lib::get_file_name_without_extension|"a" "b"|1'
-    'lib::get_file_name_without_extension|"/tmp/non-existent-file.ext"|1'
-    'lib::get_file_name_without_extension|"/etc/host.conf"|0'
-    'lib::get_file_path||1'
-    'lib::get_file_path|""|1'
-    'lib::get_file_path|"a" "b"|1'
-    'lib::get_file_path|"/tmp/non-existent-file.ext"|1'
-    'lib::get_file_path|"/etc/host.conf"|0'
-    'lib::generate_password||1'
-    'lib::generate_password|""|1'
-    'lib::generate_password|"a"|1'
-    'lib::generate_password|"1" "2"|1'
-    'lib::generate_password|"7"|1'
-    'lib::generate_password|"8"|0'
-    'lib::generate_password|"9"|0'
-    'lib::generate_password|"32"|0'
-    'lib::implode|"," "This is" "a" "test."|0'
-    'lib::implode|"," "Foo"|0'
-    'lib::implode|"" "Foo"|0'
-    'lib::implode|"" "" ""|0'
-    'lib::implode|"," ""|0'
-    'lib::implode|"," "" ""|0'
-    'lib::implode|"" ""|0'
-    'lib::implode|","|1'
-    'lib::implode||1'
-    'lib::is_empty|""|0'
-    'lib::is_empty|"a"|1'
-    'lib::is_empty|"a" "b"|1'
-    'lib::is_empty|"" ""|1'
-    'lib::is_empty||1'
-    'lib::is_integer|"69"|0'
-    'lib::is_integer|"foo"|1'
-    'lib::is_integer|"1" "2" "3"|1'
-    'lib::is_integer||1'
-    'lib::send_mail_msg||1'
-    'lib::send_mail_msg|""|1'
-    'lib::send_mail_msg|"" ""|1'
-    'lib::send_mail_msg|"" "" ""|1'
-    'lib::send_mail_msg|"" "" "" ""|1'
-    'lib::send_mail_msg|"" "" "" "" ""|1'
-    'lib::send_mail_msg|"foo@example.com" "" "" "" ""|1'
-    'lib::send_mail_msg|"foo@example.com" "foo@example.com" "" "" ""|1'
-    'lib::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "" ""|1'
-    'lib::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "Subject" ""|0'
-    'lib::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "Subject"|0'
-    'lib::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "Subject" "Body"|0'
-    'lib::send_mail_msg|"Foo <foo@example.com>" "foo@example.com" "foo@example.com" "Subject" "Body"|0'
-    'lib::send_mail_msg|"Foo <foo@example.com>" "Foo <foo@example.com>" "foo@example.com" "Subject" "Body"|0'
-    'lib::send_sms_msg||1'
-    'lib::send_sms_msg|""|1'
-    'lib::send_sms_msg|"" ""|1'
-    'lib::send_sms_msg|"foo"|1'
-    'lib::send_sms_msg|"foo" ""|1'
-    'lib::send_sms_msg|"foo" "bar"|1'
-    'lib::send_sms_msg|"17039897379" "bar"|1'
-    'lib::send_sms_msg|"+17039897379"|1'
-    'lib::send_sms_msg|"+17039897379" ""|1'
-    'lib::send_sms_msg|"+17039897379" "bar"|0'
-    'lib::str_repeat|"-" "3"|0'
-    'lib::str_repeat|"" "6"|0'
-    'lib::str_repeat|" " "9"|0'
-    'lib::str_repeat|"-" "a"|1'
-    'lib::str_repeat|"" ""|1'
-    'lib::str_repeat|"-" ""|1'
-    'lib::str_repeat||1'
-    'lib::trim||1'
-    'lib::trim|""|0'
-    'lib::trim|"abc"|0'
-    'lib::trim|"   def"|0'
-    'lib::trim|"ghi   "|0'
-    'lib::trim|"   jkl   "|0'
-    'lib::trim|"   mno   pqr   stu   "|0'
-    'lib::transliterate|"This is A string."|0'
-    'lib::transliterate|"This is A string." "So is this."|1'
-    'lib::transliterate|""|0'
-    'lib::transliterate||1'
-    'lib::validate_arg_count|"2" "1" "3"|0'
-    'lib::validate_arg_count|"4" "5" "6"|1'
-    'lib::validate_arg_count|"a" "8" "9"|1'
-    'lib::validate_arg_count|"7" "b" "9"|1'
-    'lib::validate_arg_count|"7" "8" "c"|1'
-    'lib::validate_arg_count|"7"|1'
-    'lib::validate_arg_count||1'
-    'lib::verify_dependencies|"rm" "sort" "cough"|1'
-    'lib::verify_dependencies|"rm" "ls" "whoami"|0'
+    'bfl::declare_global_display_constants|"foo" "bar"|1'
+    'bfl::declare_global_display_constants|"foo"|1'
+    'bfl::declare_global_display_constants|""|1'
+    'bfl::declare_global_display_constants||0'
+    'bfl::echo_args|"foo" "bar"|0'
+    'bfl::echo_args|"foo"|0'
+    'bfl::echo_args|""|0'
+    'bfl::echo_args||1'
+    'bfl::die|"foo" "bar"|1'
+    'bfl::die|"foo"|1'
+    'bfl::die|""|1'
+    'bfl::die||1'
+    'bfl::find_nearest_integer||1'
+    'bfl::find_nearest_integer||1'
+    'bfl::find_nearest_integer|"" ""|1'
+    'bfl::find_nearest_integer|"a" ""|1'
+    'bfl::find_nearest_integer|"3" "a e g"|1'
+    'bfl::find_nearest_integer|"3" ""|1'
+    'bfl::find_nearest_integer|"3.1" "1 4 9"|1'
+    'bfl::find_nearest_integer|"3" "1 4.1 9"|1'
+    'bfl::find_nearest_integer|"3" "1 4 9"|0'
+    'bfl::find_nearest_integer|"3" "2 4"|0'
+    'bfl::find_nearest_integer|"3" "4"|0'
+    'bfl::get_file_directory||1'
+    'bfl::get_file_directory|""|1'
+    'bfl::get_file_directory|"a" "b"|1'
+    'bfl::get_file_directory|"/tmp/non-existent-file.ext"|1'
+    'bfl::get_file_directory|"/etc/host.conf"|0'
+    'bfl::get_file_extension||1'
+    'bfl::get_file_extension|""|1'
+    'bfl::get_file_extension|"a" "b"|1'
+    'bfl::get_file_extension|"/tmp/non-existent-file.ext"|1'
+    'bfl::get_file_extension|"/etc/host.conf"|0'
+    'bfl::get_file_name||1'
+    'bfl::get_file_name|""|1'
+    'bfl::get_file_name|"a" "b"|1'
+    'bfl::get_file_name|"/tmp/non-existent-file.ext"|1'
+    'bfl::get_file_name|"/etc/host.conf"|0'
+    'bfl::get_file_name_without_extension||1'
+    'bfl::get_file_name_without_extension|""|1'
+    'bfl::get_file_name_without_extension|"a" "b"|1'
+    'bfl::get_file_name_without_extension|"/tmp/non-existent-file.ext"|1'
+    'bfl::get_file_name_without_extension|"/etc/host.conf"|0'
+    'bfl::get_file_path||1'
+    'bfl::get_file_path|""|1'
+    'bfl::get_file_path|"a" "b"|1'
+    'bfl::get_file_path|"/tmp/non-existent-file.ext"|1'
+    'bfl::get_file_path|"/etc/host.conf"|0'
+    'bfl::generate_password||1'
+    'bfl::generate_password|""|1'
+    'bfl::generate_password|"a"|1'
+    'bfl::generate_password|"1" "2"|1'
+    'bfl::generate_password|"7"|1'
+    'bfl::generate_password|"8"|0'
+    'bfl::generate_password|"9"|0'
+    'bfl::generate_password|"32"|0'
+    'bfl::implode|"," "This is" "a" "test."|0'
+    'bfl::implode|"," "Foo"|0'
+    'bfl::implode|"" "Foo"|0'
+    'bfl::implode|"" "" ""|0'
+    'bfl::implode|"," ""|0'
+    'bfl::implode|"," "" ""|0'
+    'bfl::implode|"" ""|0'
+    'bfl::implode|","|1'
+    'bfl::implode||1'
+    'bfl::is_empty|""|0'
+    'bfl::is_empty|"a"|1'
+    'bfl::is_empty|"a" "b"|1'
+    'bfl::is_empty|"" ""|1'
+    'bfl::is_empty||1'
+    'bfl::is_integer|"69"|0'
+    'bfl::is_integer|"foo"|1'
+    'bfl::is_integer|"1" "2" "3"|1'
+    'bfl::is_integer||1'
+    'bfl::send_mail_msg||1'
+    'bfl::send_mail_msg|""|1'
+    'bfl::send_mail_msg|"" ""|1'
+    'bfl::send_mail_msg|"" "" ""|1'
+    'bfl::send_mail_msg|"" "" "" ""|1'
+    'bfl::send_mail_msg|"" "" "" "" ""|1'
+    'bfl::send_mail_msg|"foo@example.com" "" "" "" ""|1'
+    'bfl::send_mail_msg|"foo@example.com" "foo@example.com" "" "" ""|1'
+    'bfl::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "" ""|1'
+    'bfl::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "Subject" ""|0'
+    'bfl::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "Subject"|0'
+    'bfl::send_mail_msg|"foo@example.com" "foo@example.com" "foo@example.com" "Subject" "Body"|0'
+    'bfl::send_mail_msg|"Foo <foo@example.com>" "foo@example.com" "foo@example.com" "Subject" "Body"|0'
+    'bfl::send_mail_msg|"Foo <foo@example.com>" "Foo <foo@example.com>" "foo@example.com" "Subject" "Body"|0'
+    'bfl::send_sms_msg||1'
+    'bfl::send_sms_msg|""|1'
+    'bfl::send_sms_msg|"" ""|1'
+    'bfl::send_sms_msg|"foo"|1'
+    'bfl::send_sms_msg|"foo" ""|1'
+    'bfl::send_sms_msg|"foo" "bar"|1'
+    'bfl::send_sms_msg|"17039897379" "bar"|1'
+    'bfl::send_sms_msg|"+17039897379"|1'
+    'bfl::send_sms_msg|"+17039897379" ""|1'
+    'bfl::send_sms_msg|"+17039897379" "bar"|0'
+    'bfl::str_repeat|"-" "3"|0'
+    'bfl::str_repeat|"" "6"|0'
+    'bfl::str_repeat|" " "9"|0'
+    'bfl::str_repeat|"-" "a"|1'
+    'bfl::str_repeat|"" ""|1'
+    'bfl::str_repeat|"-" ""|1'
+    'bfl::str_repeat||1'
+    'bfl::trim||1'
+    'bfl::trim|""|0'
+    'bfl::trim|"abc"|0'
+    'bfl::trim|"   def"|0'
+    'bfl::trim|"ghi   "|0'
+    'bfl::trim|"   jkl   "|0'
+    'bfl::trim|"   mno   pqr   stu   "|0'
+    'bfl::transliterate|"This is A string."|0'
+    'bfl::transliterate|"This is A string." "So is this."|1'
+    'bfl::transliterate|""|0'
+    'bfl::transliterate||1'
+    'bfl::validate_arg_count|"2" "1" "3"|0'
+    'bfl::validate_arg_count|"4" "5" "6"|1'
+    'bfl::validate_arg_count|"a" "8" "9"|1'
+    'bfl::validate_arg_count|"7" "b" "9"|1'
+    'bfl::validate_arg_count|"7" "8" "c"|1'
+    'bfl::validate_arg_count|"7"|1'
+    'bfl::validate_arg_count||1'
+    'bfl::verify_dependencies|"rm" "sort" "cough"|1'
+    'bfl::verify_dependencies|"rm" "ls" "whoami"|0'
   )
 }
 
@@ -165,7 +165,7 @@ declare_assertions() {
 # shellcheck disable=SC2154
 #------------------------------------------------------------------------------
 assert() {
-  lib::validate_arg_count "$#" 3 3 || exit 1
+  bfl::validate_arg_count "$#" 3 3 || exit 1
 
   declare -r function_to_test="$1"
   declare -r args="$2"
@@ -177,11 +177,11 @@ assert() {
   declare result
 
   # Test for empty strings.
-  if lib::is_empty "${function_to_test}"; then
-    lib::die "Error: \$function_to_test is a an empty string."
+  if bfl::is_empty "${function_to_test}"; then
+    bfl::die "Error: \$function_to_test is a an empty string."
   fi
-  if lib::is_empty "${expected_return_code}"; then
-    lib::die "Error: \$expected_return_code is a an empty string."
+  if bfl::is_empty "${expected_return_code}"; then
+    bfl::die "Error: \$expected_return_code is a an empty string."
   fi
 
   # Run the command. The command is run in a subshell (command substitution);
@@ -222,7 +222,7 @@ main() {
   # Declare assertions.
   declare_assertions
 
-  # We can't call lib::declare_global_display_constants() because we might test it,
+  # We can't call bfl::declare_global_display_constants() because we might test it,
   # and the function declares read only constants. If we test the function,
   # it will attempt to reassign the read only constants, causing an error.
   # Instead, we'll declare the colors here.
@@ -246,12 +246,12 @@ main() {
   declare -a pieces
 
   # Create table header lines for for displaying test results.
-  line_1=$(lib::str_repeat "=" ${cw1})
-  line_2=$(lib::str_repeat "=" ${cw2})
-  line_3=$(lib::str_repeat "=" ${cw3})
-  line_4=$(lib::str_repeat "=" ${cw4})
-  line_5=$(lib::str_repeat "=" ${cw5})
-  line_6=$(lib::str_repeat "=" ${cw6})
+  line_1=$(bfl::str_repeat "=" ${cw1})
+  line_2=$(bfl::str_repeat "=" ${cw2})
+  line_3=$(bfl::str_repeat "=" ${cw3})
+  line_4=$(bfl::str_repeat "=" ${cw4})
+  line_5=$(bfl::str_repeat "=" ${cw5})
+  line_6=$(bfl::str_repeat "=" ${cw6})
 
   # Clear the screen.
   clear
