Change format of error and warning messages.

diff --git a/docs/makedoc b/docs/makedoc
--- a/docs/makedoc
+++ b/docs/makedoc
@@ -35,7 +35,7 @@ EOT
 main() {
   # Source the Bash Function Library.
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
     exit 1
   fi
 
@@ -82,13 +82,13 @@ main() {
 
     # Find the function name (one line).
     func_name=$(grep -Eo -m1 "bfl::.+" "${file}" | sed 's/().*//') \
-      || bfl::die "Error: unable to find function name"
+      || bfl::die "Unable to find function name"
 
     # Find the function description (one entry).
     func_summary=$(grep -A1 "@function" "${file}" | \
       tail -n1 | \
       sed 's/^# *//') \
-      || bfl::die "Error: unable to find function description."
+      || bfl::die "Unable to find function description."
 
     # The sed command to format @param and @return entries:
     #
diff --git a/examples/session-info b/examples/session-info
--- a/examples/session-info
+++ b/examples/session-info
@@ -51,7 +51,7 @@ cleanup() {
 main() {
   # Source the Bash Function Library.
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
     exit 1
   fi
 
@@ -82,28 +82,28 @@ main() {
     "blue"|"cyan"|"green"|"magenta"|"red"|"yellow"|"white" )
       ;;
     * )
-      bfl::warn "Warning: specified color not supported." && usage
+      bfl::warn "The specified color not is not supported." && usage
       ;;
   esac
 
   # Get values to display.
   date_now=$(date "+%A, %B %-d, %Y") \
-    || bfl::die "Error: unable to determine date."
+    || bfl::die "Unable to determine date."
   host=$(hostname) \
-    || bfl::die "Error: unable to determine hostname ."
+    || bfl::die "Unable to determine hostname ."
   ip_address_private=$(hostname -I) \
-    || bfl::die "Error: unable to determine private IP address."
+    || bfl::die "Unable to determine private IP address."
   ip_address_public=$(curl -s --max-time 5 https://ipinfo.io/ip) \
-    || bfl::die "Error: unable to determine public IP address."
+    || bfl::die "Unable to determine public IP address."
   time_now=$(date "+%-l:%M %p %Z") \
-    || bfl::die "Error: unable to determine time."
+    || bfl::die "Unable to determine time."
   user=$(whoami) \
-    || bfl::die "Error: unable to determine user."
+    || bfl::die "Unable to determine user."
 
   # Create border.
   width=$((21+${#date_now}))
   border=$(bfl::repeat "=" "${width}") \
-    || bfl::die "Error: unable to create a repeated string."
+    || bfl::die "Unable to create a repeated string."
 
   # Display the banner.
   printf "%b\\n" "${!color}" # Indirect variable expansion; see man bash.
diff --git a/templates/script b/templates/script
--- a/templates/script
+++ b/templates/script
@@ -57,7 +57,7 @@ cleanup() {
 main() {
   # Source the Bash Function Library.
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
     exit 1
   fi
 
@@ -83,8 +83,8 @@ main() {
   declare ham="Seamus" # TODO
 
   # Verify argument values.
-  bfl::is_empty "$foo" && bfl::die "Error: foo is required." # TODO
-  bfl::is_empty "$bar" && bfl::die "Error: bar is required." # TODO
+  bfl::is_empty "$foo" && bfl::die "Foo is required." # TODO
+  bfl::is_empty "$bar" && bfl::die "Bar is required." # TODO
 
   # TODO
   printf "%s\\n" "${foo}, ${bar}, ${wibble}, ${wobble}, ${eggs}, and ${ham}."
diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -205,10 +205,10 @@ assert() {
 
   # Test for empty strings.
   if bfl::is_empty "${function_to_test}"; then
-    bfl::die "Error: \$function_to_test is a an empty string."
+    bfl::die "\$function_to_test is a an empty string."
   fi
   if bfl::is_empty "${expected_return_code}"; then
-    bfl::die "Error: \$expected_return_code is a an empty string."
+    bfl::die "\$expected_return_code is a an empty string."
   fi
 
   # Run the command. The command is run in a subshell (command substitution);
@@ -242,7 +242,7 @@ assert() {
 #------------------------------------------------------------------------------
 main() {
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
-    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
     exit 1
   fi
 
