Unified code

diff --git a/docs/makedoc b/docs/makedoc
--- a/docs/makedoc
+++ b/docs/makedoc
@@ -7,9 +7,9 @@
 
 #------------------------------------------------------------------------------
 # @function
-# Displays usage message.
+#   Displays usage message.
 #
-# @return string $msg
+# @return String $msg
 #   The usage message.
 #------------------------------------------------------------------------------
 usage() {
@@ -27,10 +27,9 @@ EOT
 
 #------------------------------------------------------------------------------
 # @function
-# Main function.
-#
-# shellcheck disable=1090
+#   Main function.
 #------------------------------------------------------------------------------
+# shellcheck disable=1090
 main() {
   # Source the Bash Function Library.
   if ! source "${BASH_FUNCTION_LIBRARY}"; then
@@ -68,79 +67,73 @@ main() {
   footer="*Last updated: $(date --iso-8601=s).*"
 
   # Loop through the files.
-  for file in "$(dirname "${BASH_FUNCTION_LIBRARY}")"/_*; do
+  for file in "${BASH_FUNCTION_LIBRARY%/*}"/_*; do    #  "$(dirname "${BASH_FUNCTION_LIBRARY}")"
 
-    # Set the headers for each section. Need to do this each time through the
-    # loop because one or more may be pluralized if there is more than one.
-    header_examples="Example"
-    header_params="Parameter"
-    header_returns="Return"
+      # Set the headers for each section. Need to do this each time through the
+      # loop because one or more may be pluralized if there is more than one.
+      header_examples="Example"
+      header_params="Parameter"
+      header_returns="Return"
 
-    # Find the function name (one line).
-    func_name=$(grep -Eo -m1 "bfl::.+" "${file}" | sed 's/().*//') \
-      || bfl::die "Unable to find function name"
+      # Find the function name (one line).
+      func_name=$(grep -Eo -m1 "bfl::.+" "${file}" | sed 's/().*//') \
+        || bfl::die "Unable to find function name"
 
-    # Find the function description (one entry).
-    func_summary=$(grep -A1 "@function" "${file}" | \
-      tail -n1 | \
-      sed 's/^# *//') \
-      || bfl::die "Unable to find function description."
+      # Find the function description (one entry).
+      func_summary=$(grep -A1 "@function" "${file}" | tail -n1 | sed 's/^# *//') \
+        || bfl::die "Unable to find function description."
 
-    # The sed command to format @param and @return entries:
-    #
-    #   1. Remove leading "#" and spaces from each line.
-    #   2. Add ">" to the beginning of each line.
-    #   3. Replace ">@tag " with a newline.
+      # The sed command to format @param and @return entries:
+      #
+      #   1. Remove leading "#" and spaces from each line.
+      #   2. Add ">" to the beginning of each line.
+      #   3. Replace ">@tag " with a newline.
 
-    # Find the function parameters (zero or more entries).
-    set +e
-    func_params=$(grep -A1 --no-group-separator "# *@param" "${file}" | \
-      sed 's/^# *// ; s/^/>/ ; s/>@param /\\n/')
-    [[ "$(grep -c "# *@param" "${file}")" -gt "1" ]] && header_params+="s"
-    set -e
+      # Find the function parameters (zero or more entries).
+      set +e
+      func_params=$(grep -A1 --no-group-separator "# *@param" "${file}" | \
+        sed 's/^# *// ; s/^/>/ ; s/>@param /\\n/')
+      [[ "$(grep -c "# *@param" "${file}")" -gt "1" ]] && header_params+="s"
+      set -e
 
-    # Find the function returns (zero or more entries).
-    set +e
-    func_returns=$(grep -A1 --no-group-separator "# *@return" "${file}" | \
-      sed 's/^# *// ; s/^/>/ ; s/>@return /\\n/')
-    [[ "$(grep -c "# *@return" "${file}")" -gt "1" ]] && header_returns+="s"
-    set -e
+      # Find the function returns (zero or more entries).
+      set +e
+      func_returns=$(grep -A1 --no-group-separator "# *@return" "${file}" | \
+        sed 's/^# *// ; s/^/>/ ; s/>@return /\\n/')
+      [[ "$(grep -c "# *@return" "${file}")" -gt "1" ]] && header_returns+="s"
+      set -e
 
-    # The sed command to format @example entries:
-    #
-    #   1. Delete the line containing the @example tag.
-    #   2. Remove leading "#" and spaces from each line.
+      # The sed command to format @example entries:
+      #
+      #   1. Delete the line containing the @example tag.
+      #   2. Remove leading "#" and spaces from each line.
 
-    # Find the function examples (zero or more entries).
-    set +e
-    func_examples=$(grep -A1 --no-group-separator "# *@example" "${file}" | \
-      sed '/.*@example.*/d ; s/^# *//' )
-    [[ "$(grep -c "# *@example" "${file}")" -gt "1" ]] && header_examples+="s"
-    set -e
+      # Find the function examples (zero or more entries).
+      set +e
+      func_examples=$(grep -A1 --no-group-separator "# *@example" "${file}" | \
+        sed '/.*@example.*/d ; s/^# *//' )
+      [[ "$(grep -c "# *@example" "${file}")" -gt "1" ]] && header_examples+="s"
+      set -e
 
-    # Surround the examples with 3 backticks.
-    func_examples="\\n${btx3}bash\\n${func_examples}\\n${btx3}\\n"
+      # Surround the examples with 3 backticks.
+      func_examples="\\n${btx3}bash\\n${func_examples}\\n${btx3}\\n"
 
-    # Add to the table of contents.
-    toc+="* [${func_name}](#${func_name//::/})\\n"
+      # Add to the table of contents.
+      toc+="* [${func_name}](#${func_name//::/})\\n"
 
-    # Add to the body.
-    body+="## ${func_name}\\n\\n"
-    body+="${func_summary}\\n\\n"
-    ! bfl::is_empty "${func_params}" && body+="**${header_params}**\\n"
-    ! bfl::is_empty "${func_params}" && body+="${func_params}\\n\\n"
-    ! bfl::is_empty "${func_returns}" && body+="**${header_returns}**\\n"
-    ! bfl::is_empty "${func_returns}" && body+="${func_returns}\\n\\n"
-    ! bfl::is_empty "${func_examples}" && body+="**${header_examples}**\\n"
-    ! bfl::is_empty "${func_examples}" && body+="${func_examples}\\n"
+      # Add to the body.
+      body+="## ${func_name}\\n\\n"
+      body+="${func_summary}\\n\\n"
+      bfl::is_empty "${func_params}"   || body+="**${header_params}**\\n"
+      bfl::is_empty "${func_params}"   || body+="${func_params}\\n\\n"
+      bfl::is_empty "${func_returns}"  || body+="**${header_returns}**\\n"
+      bfl::is_empty "${func_returns}"  || body+="${func_returns}\\n\\n"
+      bfl::is_empty "${func_examples}" || body+="**${header_examples}**\\n"
+      bfl::is_empty "${func_examples}" || body+="${func_examples}\\n"
   done
 
-  printf  "%b\\n\\n%b\\n%b---\\n%b\\n" \
-    "${header}" \
-    "${toc}" \
-    "${body}" \
-    "${footer}" \
-    > "$(dirname "${BASH_FUNCTION_LIBRARY}")/docs/${output_file_name}"
+  printf  "%b\\n\\n%b\\n%b---\\n%b\\n" "${header}" "${toc}" "${body}" "${footer}" \
+      > "${BASH_FUNCTION_LIBRARY%/*}/docs/${output_file_name}"    # "$(dirname "${BASH_FUNCTION_LIBRARY}")"
 }
 
 set -euo pipefail
diff --git a/no_bats_tests b/no_bats_tests
--- a/no_bats_tests
+++ b/no_bats_tests
@@ -2,18 +2,19 @@
 
 #------------------------------------------------------------------------------
 # @function
-# Tests a function to see if its return code matches the expected return code.
+#   Tests a function to see if its return code matches the expected return code.
 #
-# @param string $function_to_test
+# @param String $function_to_test
 #   The function to be tested.
-# @param string $args
-#   The arguments to pass to the function.
-# @param string $expected_return_code
-#   The expected return code (0 or 1).
 #
+# @param String $args
+#   The arguments to pass to the function.
+#
+# @param String $expected_return_code
+#   The expected return code (0 or 1).
+#------------------------------------------------------------------------------
 # shellcheck disable=SC2059
 # shellcheck disable=SC2154
-#------------------------------------------------------------------------------
 assert() {
   bfl::verify_arg_count "$#" 3 3 || exit 1
 
@@ -54,22 +55,18 @@ assert() {
 
 #------------------------------------------------------------------------------
 # @function
-# Main function.
+#   Main function.
 #
-# @param array global $assertions
+# @param Array global $assertions
 #   Global array created by declare_assertions().
-#
+#------------------------------------------------------------------------------
 # shellcheck disable=SC1090
 # shellcheck disable=SC2034
 # shellcheck disable=SC2059
-#------------------------------------------------------------------------------
 main() {
-  if ! source "${BASH_FUNCTION_LIBRARY}"; then
-      printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2
-      exit 1
-  fi
+  source "${BASH_FUNCTION_LIBRARY}" || { printf "Error. Unable to source BASH_FUNCTION_LIBRARY.\\n" 1>&2 ; exit 1; }
 
-  d="$(dirname $BASH_FUNCTION_LIBRARY)/test"
+  d="${BASH_FUNCTION_LIBRARY%/*}"/test  # "$(dirname $BASH_FUNCTION_LIBRARY)/test"
   for f in `ls "$d"/`; do
       unset assertions
       source "$BASH_FUNCTION_LIBRARY"/test/"$f"
