Improve error handling
Fixes #9.

diff --git a/docs/makedoc b/docs/makedoc
--- a/docs/makedoc
+++ b/docs/makedoc
@@ -12,7 +12,12 @@
 # shellcheck disable=1090
 #------------------------------------------------------------------------------
 main() {
-  source "${BASH_FUNCTION_LIBRARY}"
+  if ! source "${BASH_FUNCTION_LIBRARY}"; then
+    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    exit 1
+  fi
+
+  lib::validate_arg_count "$#" 0 0 || usage
   lib::declare_global_display_constants
 
   declare body
@@ -30,11 +35,10 @@ main() {
   toc="## Table of Contents\\n\\n"
 
   for file_path in "$(dirname "${BASH_FUNCTION_LIBRARY}")"/_*; do
-
-    function_name=$(grep "() {" "${file_path}")
+    function_name=$(grep "() {" "${file_path}") || lib::die
     function_name="${function_name::-4}"
 
-    function_desc=$(grep -A1 @function "${file_path}" | tail -1)
+    function_desc=$(grep -A1 @function "${file_path}" | tail -1) || lib::die
     function_desc="${function_desc:2}"
 
     # The following sed command...
@@ -43,6 +47,7 @@ main() {
     #   3) Adds two spaces to the end of each line
     #   4) Places '**' on each side of '@param' and '@return'
     set +e
+
     function_params=$(grep -A1 --no-group-separator "@param" "${file_path}" | sed 's/^# //; /^#$/d; s/$/  /; s/@param/**@param**/')
     function_return=$(grep -A1 --no-group-separator "@return" "${file_path}" | sed 's/^# //; /^#$/d; s/$/  /; s/@return/**@return**/')
     set -e
diff --git a/examples/repeat b/examples/repeat
--- a/examples/repeat
+++ b/examples/repeat
@@ -28,7 +28,11 @@ usage() {
 # shellcheck disable=1090
 #------------------------------------------------------------------------------
 main() {
-  source "${BASH_FUNCTION_LIBRARY}"
+  if ! source "${BASH_FUNCTION_LIBRARY}"; then
+    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    exit 1
+  fi
+
   lib::declare_global_display_constants
   lib::validate_arg_count "$#" 2 2 || usage
 
@@ -36,7 +40,7 @@ main() {
   declare -r multiplier="$2"
   declare repeated_string
 
-  repeated_string=$(lib::str_repeat "${string_to_repeat}" "${multiplier}")
+  repeated_string=$(lib::str_repeat "${string_to_repeat}" "${multiplier}") || lib::die
   printf "%s\\n" "${repeated_string}"
 }
 
diff --git a/examples/template b/examples/template
--- a/examples/template
+++ b/examples/template
@@ -40,7 +40,11 @@ cleanup() {
 # shellcheck disable=1090
 #------------------------------------------------------------------------------
 main() {
-  source "${BASH_FUNCTION_LIBRARY}"
+  if ! source "${BASH_FUNCTION_LIBRARY}"; then
+    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    exit 1
+  fi
+
   lib::declare_global_display_constants
   lib::validate_arg_count "$#" 2 2 || usage
 
diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -30,10 +30,10 @@ declare_assertions() {
     'lib::echo_args|"foo"|0'
     'lib::echo_args|""|0'
     'lib::echo_args||1'
-    'lib::err|"foo" "bar"|1'
-    'lib::err|"foo"|0'
-    'lib::err|""|1'
-    'lib::err||1'
+    'lib::die|"foo" "bar"|1'
+    'lib::die|"foo"|1'
+    'lib::die|""|1'
+    'lib::die||1'
     'lib::find_nearest_integer||1'
     'lib::find_nearest_integer||1'
     'lib::find_nearest_integer|"" ""|1'
@@ -165,7 +165,8 @@ declare_assertions() {
 # shellcheck disable=SC2154
 #------------------------------------------------------------------------------
 assert() {
-  lib::validate_arg_count "$#" 3 3 || return 1
+  lib::validate_arg_count "$#" 3 3 || exit 1
+
   declare -r function_to_test="$1"
   declare -r args="$2"
   declare -r expected_return_code="$3"
@@ -177,15 +178,14 @@ assert() {
 
   # Test for empty strings.
   if lib::is_empty "${function_to_test}"; then
-    lib::err "Error: \$function_to_test is a an empty string."
-    return 1
+    lib::die "Error: \$function_to_test is a an empty string."
   fi
   if lib::is_empty "${expected_return_code}"; then
-    lib::err "Error: \$expected_return_code is a an empty string."
-    return 1
+    lib::die "Error: \$expected_return_code is a an empty string."
   fi
 
-  # Run the command.
+  # Run the command. The command is run in a subshell (command substitution);
+  # exit calls will terminate the subshell, not this script.
   cmd=$(printf "%s %s" "${function_to_test}" "${args}")
   cmd_output=$(eval "${cmd}" 2>&1)
   actual_return_code="$?"
@@ -214,7 +214,10 @@ assert() {
 # shellcheck disable=SC2059
 #------------------------------------------------------------------------------
 main() {
-  source "${BASH_FUNCTION_LIBRARY}"
+  if ! source "${BASH_FUNCTION_LIBRARY}"; then
+    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
+    exit 1
+  fi
 
   # Declare assertions.
   declare_assertions
@@ -228,7 +231,7 @@ main() {
   declare -g green="\\e[0;32m"
   declare -g reset="\\e[0m"
 
-  # Declare column widths for displaying test results.
+  # Declare column widths (global constants) for displaying test results.
   declare -rg cw1=6     # Width of column 1: Result (PASS/FAIL)
   declare -rg cw2=37    # Width of column 2: Function
   declare -rg cw3=33    # Width of column 3: Arguments
